version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    parameters:
      s3-bucket-name:
        type: string
        default: test-api-circleci
      stack-name:
        type: string
        default: testapistack
      
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Install AWS SAM CLI
          command: |
            pip install aws-sam-cli
      - run:
          name: Package and Deploy with SAM
          command: |
            sam package --template-file restapitest.yml --output-template-file packaged.yml --s3-bucket <<parameters.s3-bucket-name>>
            sam deploy --template-file packaged.yml --stack-name <<parameters.stack-name>> --capabilities CAPABILITY_IAM

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          s3-bucket-name: $testapibucket
          stack-name: $testapistackname
          filters:
            branches:
              only: main
                                
              
