version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    parameters:
      s3-bucket-name:
        type: string
        default: test-api-circleci
      stack-name:
        type: string
        default: testapistack
      
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - run:
          name: Install AWS SAM CLI
          command: |
            pip install aws-sam-cli
      - run:
          name: configure AWS credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION      
      - run:
          name: Package and Deploy with SAM
          command: |
            sam package --template-file restapitest.yml --output-template-file packaged.yml --s3-bucket <<parameters.s3-bucket-name>>
            sam deploy --template-file packaged.yml --stack-name <<parameters.stack-name>> --capabilities CAPABILITY_IAM

workflows:
  version: 2
  testdeploy:
    jobs:
      - deploy:
          name: deploy-restapi
          context: aws-credential-dev
          s3-bucket-name: $testapibucket
          stack-name: $testapistackname
          filters:
            branches:
              only: main
                                
              
